samples:
  SRR1039508: rawData/ecoli_p6_25x.filtered.fastq.gz

assembly:
  genome_size: 4.5m
  correction:
    error_rate: 0.12
    min_read_length: 4000
    min_overlap: 1000
  trimming:
    error_rate: 0.105
    min_read_length: 5000  
    min_overlap: 1000
    mer_distinct: 0.975
  assembly:
    error_rate: 0.105
    min_read_length: 7000
    min_overlap: 1000
    mer_distinct: 0.975

resources:
  correction:
    threads: 15
    mem_gb: 120
  trimming:
    threads: 15  
    mem_gb: 120
  assembly:
    threads: 15
    mem_gb: 120
  polish:
    Threads: 8
    Ram: 64
    Disk: 30
  annotation:
    threads: 4
    mem_gb: 32
statRam: 8
statDisk: 20
statThreads: 4

bwaRam: 16
bwaDisk: 60
bwaThreads: 12

#assembly stats
stats: scripts/contig-stats.pl
